<a href="https://colab.research.google.com/github/theSavageseens/Analyzer/blob/master/Week_6_review_stat_random_Tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1- Write a Python program to count the number of even and odd numbers from a series of numbers.**

Input: `(1, 2, 3, 4, 5, 6, 7, 8, 9)`

Output: 

Number of even numbers: `4`

Number of odd numbers: `5`

In [1]:
input_num = (1, 2, 3, 4, 5, 6, 7, 8, 9)

odd = 0
even = 0

for x in input_num:
  if x % 2 == 0:
    even = even + 1
  if x % 2 != 0:
    odd = odd + 1
print("Number of even numbers: ", even)
print("Number of odd numbers: ", odd)
  

Number of even numbers:  4
Number of odd numbers:  5


**2- Write a Python function to calculate the factorial of a number (a non-negative integer). The function accepts the number as an argument.**

In [11]:
def factorial(n):
  fact = 1
  for i in range(1, n+1):
    fact *= i
  return fact    


factorial(4)

24

**3- Write a Python program to calculate the sum of the positive and negative numbers of a given list of numbers using lambda function.**

Original list: `[2, 4, -6, -9, 11, -12, 14, -5, 17]`

Sum of the positive numbers:  `-32`

Sum of the negative numbers:  `48`

In [12]:
list1 = [2, 4, -6, -9, 11, -12, 14, -5, 17]
print("Original list: ", list1)

sum_pos_num = list(filter(lambda list1: list1 > 0, list1))
sum_neg_num = list(filter(lambda list1: list1 < 0, list1))

print("Sum of the positive numbers: ", sum(sum_pos_num))
print("Sum of the negative numbers: ", sum(sum_neg_num))

Original list:  [2, 4, -6, -9, 11, -12, 14, -5, 17]
Sum of the positive numbers:  48
Sum of the negative numbers:  -32


**4- Write a Python program to add three given lists using Python map and lambda.**

Input: 

`[1, 2, 3]`

`[4, 5, 6]`

`[7, 8, 9]`

Output:

`[12, 15, 18]`

In [14]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]
num3 = [7, 8, 9]

num_out = map(lambda a,b,c: a+b+c, num1,num2,num3)

print("Input:")
print(num1)
print(num2)
print(num3)
print("Output:")
print(list(num_out))



Input:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Output:
[12, 15, 18]


**5- Write a Python program to triple all numbers of a given list of integers. Use Python map.**

Input: `[1, 2, 3, 4, 5, 6, 7]`

Output: `[3, 6, 9, 12, 15, 18, 21]`


In [16]:
inp = [1, 2, 3, 4, 5, 6, 7]
oup = map(lambda a: 3*a, inp)

print("Input: ", inp)
print("Output: ",list(oup))

Input:  [1, 2, 3, 4, 5, 6, 7]
Output:  [3, 6, 9, 12, 15, 18, 21]


**6- Write a Python program to construct the following pattern, using a nested for loop.**

`*`\
`* *`\
`* * *`\
`* * * *`\
`* * * * *`\
`* * * *`\
`* * *`\
`* *`\
`*`

In [17]:
for i in range(5):
  for j in range(i):
    print('* ', end="")
  print('')

for i in range(5,0,-1):
  for j in range(i):
    print('* ', end="")
  print('')


* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


**7- Write a Python program to calculate mean, standard deviation and variance of a list with and without Numpy.**

In [24]:
import math

def mean(data):
  n = len(data)
  mean = sum(data) / n
  return mean

def variance(data):
  n = len(data)
  mean = sum(data) / n
  deviations = [(x - mean) ** 2 for x in data]
  variance = sum(deviations) / n
  return variance

def deviation(data):
  n = len(data)
  mean = sum(data) / n
  deviation = [(x - mean) ** 2 for x in data]
  var = variance(data)
  sd = math.sqrt(var)
  return sd

list1 = [1,2,3,4,5,6,7,8,9]
print(mean(list1))
print(deviation(list1))
print(variance(list1))

5.0
2.581988897471611
6.666666666666667


**8- Write a NumPy program to get the minimum and maximum value of a given array along the second axis.**

In [9]:
import numpy as np

matrix = np.arange(6).reshape((2,3))
print(matrix)

max = np.amax(matrix,1)
min = np.amin(matrix,1)

print(max)
print(min)

[[0 1 2]
 [3 4 5]]
[2 5]
[0 3]


**9- Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.**

In [11]:
import numpy as np

matrix = np.arange(6).reshape((2,3))
print(matrix)

diff = np.amax(matrix,1) - np.amin(matrix,1)

print(diff)

[[0 1 2]
 [3 4 5]]
[2 2]


**10- Write a NumPy program to generate six random integers between 10 and 30.**

In [12]:
import numpy as np

list1 = np.random.randint(low=10, high=30, size=6)

print(list1)

[21 23 19 15 16 29]


**11- Write a NumPy program to generate five random numbers from the normal distribution.**

In [14]:
import numpy as np

list2 = np.random.normal(size=5)

print(list2)

[1.14013426 0.16043491 0.32992324 0.68397259 0.20972144]


**12- Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.**

In [15]:
import numpy as np

matrix1 = np.random.random((5,5))
print(matrix1)

min = np.amin(matrix1)
max = np.amax(matrix1)

print(min)
print(max)

[[0.23128399 0.31397769 0.29779649 0.30533094 0.48345809]
 [0.36453115 0.13746497 0.94945329 0.45244039 0.20489725]
 [0.19611332 0.34173613 0.17121015 0.22643627 0.70207525]
 [0.27497459 0.94908065 0.83730121 0.74344695 0.40137438]
 [0.17506079 0.09278893 0.77437684 0.00441698 0.22911214]]
0.004416975572885229
0.9494532897028657


**13- Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.**

In [16]:
import numpy as np

matrix2 = np.random.random((10,4))
print(matrix2)

matrix3 = matrix2[0:5,0:]
print(matrix3)

[[0.92307936 0.07152269 0.55706811 0.74553619]
 [0.01436096 0.35631457 0.31458429 0.46222676]
 [0.09255784 0.80268065 0.70088264 0.9476705 ]
 [0.60399237 0.54535064 0.69679862 0.88349133]
 [0.42393199 0.57117114 0.58182894 0.09026694]
 [0.62035164 0.55892681 0.47487598 0.57054182]
 [0.5543606  0.24741044 0.30763351 0.20908706]
 [0.72057645 0.45829419 0.97665641 0.8857024 ]
 [0.6261525  0.83325362 0.28193437 0.37666805]
 [0.01658543 0.45001402 0.02209635 0.2028025 ]]
[[0.92307936 0.07152269 0.55706811 0.74553619]
 [0.01436096 0.35631457 0.31458429 0.46222676]
 [0.09255784 0.80268065 0.70088264 0.9476705 ]
 [0.60399237 0.54535064 0.69679862 0.88349133]
 [0.42393199 0.57117114 0.58182894 0.09026694]]
